name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      RUBOCOP_CACHE_ROOT: tmp/rubocop
    steps:
      - uses: actions/checkout@v7
      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run RuboCop
        run: bin/lint --format github --format clang

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        ruby-version: [ "3.3", "3.4", "4.0" ]
    steps:
      - uses: actions/checkout@v7
      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run Tests
        run: bin/test

